### PR TITLE
Update to text file input read and conversion into graph work so far

### PR DESCRIPTION
**Pull request by fco2**
I have already implemented the algorithm for generating the graphs for all the user inputs. All that is left is for me to incorporate it into the points class i created. I will do that later today

### CODE REVIEW

**Comment by AaronBattershell** [comment]
Can you pull from the master branch and then make another pull request?

Edit: I say this because I noticed your fork was pretty far behind and I don't want to mess up the master branch.

**Comment by thehexia** [comment]
Also, I believe you forgot to add some files or something since none of the files you committed have the changes you're talking about.

**Comment by fco2** [comment]
Did you guys see any new files called points.hpp and s.txt?

**Comment by AaronBattershell** [comment]
I don't see those files in your fork. I think you need to use "git add [file_name]" on your newly created files.

**Pull request closed without merging**
